- name: Testing variable precedence
  hosts: mongodb
  vars: 
    PRENAME: ThisisPlayLevel
  vars_files: 
    - variablefile.yaml
  vars_prompt: 
  - name: PRENAME
    prompt: please enter precedence username
    private: false #you can see the value
  tasks: 
  - name: Printing the value with prioritize
      ansible.builtin.debug:
        msg: "this is the value of priority:  {{PRENAME}}"
