- name: Ensure 'roboshop' user exists
  hosts: localhost #all
  

  tasks:
    - name: Check if user 'roboshop' exists
      ansible.builtin.command: id roboshop
      register: user_check
      ignore_errors: yes  # Prevent failure if the user does not exist

    - name: Create user 'roboshop' if not exists
      become: yes  # Run as root
      ansible.builtin.user:      
        name: roboshop
        state: present
        #shell: /bin/bash
        create_home: yes
      when: user_check.rc != 0  # Only create if user does not exist

    - name: Display message
      ansible.builtin.debug:
        msg: "User 'roboshop' has been created .."
      when: user_check.rc != 0  # Only createit will display if user does not exist
    - name: Display message
      ansible.builtin.debug:
        msg: "User 'roboshop' is already exists."
      when: user_check.rc == 0  # Only write if user exist
