- name: install packages throuh loop
  hosts: mongodb
  become: yes
  tasks:  #install packages in loop with list of map
    - name: install packages
    ansible.builtin.yum:
      name: "{{item.name}}"
      state: "{{item.state}}"
      #this will refered with item,name
    loop:
    - {name: 'nginx' , state: 'installed'}
    - {name: 'postfix' , state: 'installed'}
    - {name: 'mailx' , state: 'absent'}
    - {name: 'mysql' , state: 'absent'}

  # loop of list 
  #  - nginx
  #  = postfix
  #  - mailx
  #  - mysql
  # will refered with item
